/**
 * REAL RLS / grant tests against the TARGET dev project (never the SOURCE).
 * Uses the anon key, an anonymous Auth session, a verified organizer session (magic link
 * generated by the admin API — no e-mail is sent) and the service role for setup/cleanup.
 * Every row created lives under a sandbox territory (`mg-99xxxxx`, an impossible IBGE code)
 * and is removed in afterAll by cascading from that territory; test users are deleted.
 *
 * Run: npm run test:db   (loads .dev.vars; skipped when TARGET credentials are absent)
 */
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { loadDevVars } from '../../scripts/db/load-env.ts';

loadDevVars();
const URL_ = process.env.SUPABASE_TARGET_URL ?? '';
const ANON = process.env.SUPABASE_TARGET_ANON_KEY ?? '';
const SERVICE = process.env.SUPABASE_TARGET_SERVICE_ROLE_KEY ?? '';
const configured = Boolean(URL_ && ANON && SERVICE) && new URL(URL_ || 'http://x').hostname.startsWith('wnclh');

const opts = { auth: { persistSession: false, autoRefreshToken: false } };
const PRIVATE_TABLES = [
  'profiles',
  'admins',
  'group_proposals',
  'group_managers',
  'activity_rsvps',
  'audit_events',
  'abuse_events',
  'turnstile_tokens_used',
];
const DENIED = [401, 403, 404, 406];

describe.skipIf(!configured)('RLS & grants on TARGET dev', () => {
  const tag = `${Date.now().toString(36)}${Math.floor(Math.random() * 1e4)}`;
  const muni = `mg-99${String(Math.floor(Math.random() * 1e5)).padStart(5, '0')}`;
  const hood = `${muni}-rls-${tag}`;
  const userIds: string[] = [];

  let svc: SupabaseClient;
  let anon: SupabaseClient;
  let anonSession: SupabaseClient; // signInAnonymously
  let anonUserId = '';
  let organizer: SupabaseClient; // permanent + verified
  let organizerId = '';
  let otherOrganizerId = '';
  const ids = { activeGroup: '', pendingGroup: '', published: '', pending: '', otherPending: '', cancelled: '', proposal: '' };
  const admins: string[] = [];

  async function createUser(label: string, confirm = true): Promise<string> {
    const { data, error } = await svc.auth.admin.createUser({
      email: `mm-rls-${label}+${tag}@example.org`,
      email_confirm: confirm,
    });
    if (error || !data.user) throw new Error(`createUser ${label}: ${error?.code}`);
    userIds.push(data.user.id);
    return data.user.id;
  }

  async function insertActivity(creator: string, status: string, title: string): Promise<string> {
    const { data, error } = await svc
      .from('activities')
      .insert({
        creator_user_id: creator,
        territory_id: hood,
        title,
        type: 'encontro',
        description: 'descrição interna <b>bruta</b>',
        description_sanitized: 'descrição pública',
        starts_at: new Date(Date.now() + 7 * 86_400_000).toISOString(),
        public_address: 'Rua de Teste RLS, 1',
        location_lon: -43.9,
        location_lat: -19.9,
        status,
        public_contact_opt_in: true,
        public_contact_type: 'instagram',
        public_contact_value: '@contato_rls',
        review_reason: 'nota interna de moderacao',
      })
      .select('id')
      .single();
    if (error || !data) throw new Error(`insert activity: ${error?.code}`);
    return data.id as string;
  }

  beforeAll(async () => {
    svc = createClient(URL_, SERVICE, opts);
    anon = createClient(URL_, ANON, opts);

    const t = await svc.from('territories').insert([
      { id: muni, type: 'municipality', name: `RLS Teste ${tag}`, normalized_name: `rls teste ${tag}`, slug: muni, data_quality: 'demo' },
      { id: hood, type: 'neighborhood', name: 'RLS Bairro', normalized_name: 'rls bairro', slug: hood, parent_id: muni, data_quality: 'demo' },
    ]);
    if (t.error) throw new Error(`territories: ${t.error.code}`);

    const g = await svc
      .from('whatsapp_groups')
      .insert([
        { territory_id: hood, display_name: 'RLS ativo', join_url: `https://chat.whatsapp.com/RLSactive${tag}`, status: 'active' },
        { territory_id: hood, display_name: 'RLS pendente', join_url: `https://chat.whatsapp.com/RLSpending${tag}`, status: 'pending' },
      ])
      .select('id,status');
    if (g.error || !g.data) throw new Error(`groups: ${g.error?.code}`);
    ids.activeGroup = g.data.find((r) => r.status === 'active')!.id as string;
    ids.pendingGroup = g.data.find((r) => r.status === 'pending')!.id as string;

    organizerId = await createUser('org');
    otherOrganizerId = await createUser('org2');
    ids.published = await insertActivity(organizerId, 'published', 'RLS publicada');
    ids.pending = await insertActivity(organizerId, 'pending_review', 'RLS pendente propria');
    ids.otherPending = await insertActivity(otherOrganizerId, 'pending_review', 'RLS pendente alheia');
    ids.cancelled = await insertActivity(organizerId, 'cancelled', 'RLS cancelada');

    // verified organizer session through a magic link generated by the admin API (no e-mail sent)
    const link = await svc.auth.admin.generateLink({ type: 'magiclink', email: `mm-rls-org+${tag}@example.org` });
    organizer = createClient(URL_, ANON, opts);
    const ver = await organizer.auth.verifyOtp({ type: 'magiclink', token_hash: link.data.properties?.hashed_token ?? '' });
    if (ver.error) throw new Error(`organizer session: ${ver.error.code}`);

    anonSession = createClient(URL_, ANON, opts);
    const s = await anonSession.auth.signInAnonymously();
    if (s.error || !s.data.user) throw new Error(`anonymous sign-in: ${s.error?.code}`);
    anonUserId = s.data.user.id;
    userIds.push(anonUserId);
    await svc.rpc('svc_create_profile', {
      p_user_id: anonUserId,
      p_display_name: 'Perfil RLS',
      p_email: `mm-rls-profile+${tag}@example.org`,
      p_phone: '+5531999990000',
      p_territory_id: hood,
      p_consent_version: 'v1',
      p_contact_opt_in: false,
      p_email_state: 'pending',
    });

    for (const label of ['admin1', 'admin2']) {
      const id = await createUser(label);
      const r = await svc.rpc('svc_grant_admin', { p_user: id });
      if (r.error) throw new Error(`grant admin: ${r.error.code}`);
      admins.push(id);
    }
    const p = await svc.rpc('svc_create_group_proposal', {
      p_territory_id: hood,
      p_name: 'RLS proposta',
      p_join_url: `https://chat.whatsapp.com/RLSproposal${tag}`,
      p_proposer_name: 'Proponente RLS',
      p_proposer_email: `mm-rls-proposer+${tag}@example.org`,
      p_proposer_phone: '+5531988880000',
      p_proposer_user_id: null as unknown as string,
      p_consent_version: 'v1',
      p_idempotency_hash: `rls-${tag}`,
      p_fingerprint_hash: null as unknown as string,
    });
    if (p.error) throw new Error(`proposal: ${p.error.code}`);
    ids.proposal = (p.data as { id: string }).id;
  });

  afterAll(async () => {
    if (!svc) return;
    // cascades: groups, proposals, managers, activities, rsvps
    await svc.from('territories').delete().eq('id', hood);
    await svc.from('territories').delete().eq('id', muni);
    for (const id of userIds) await svc.auth.admin.deleteUser(id); // cascades profiles/admins
  });

  describe('app_private is not reachable through the Data API', () => {
    it.each(PRIVATE_TABLES)('anon cannot read app_private.%s (public path or Accept-Profile)', async (table) => {
      const viaPublic = await anon.from(table).select('*').limit(1);
      expect(viaPublic.data).toBeNull();
      expect(DENIED).toContain(viaPublic.status);
      const viaProfile = await anon.schema('app_private').from(table).select('*').limit(1);
      expect(viaProfile.data).toBeNull();
      expect(DENIED).toContain(viaProfile.status);
    });

    it('anonymous session cannot read any profile (incl. its own) directly', async () => {
      const r = await anonSession.schema('app_private').from('profiles').select('*');
      expect(r.data).toBeNull();
      expect(DENIED).toContain(r.status);
      const r2 = await anonSession.from('profiles').select('*');
      expect(r2.data).toBeNull();
    });

    it('service-only RPCs are not executable by anon or authenticated (incl. svc_grant_admin)', async () => {
      const calls: [SupabaseClient, string, Record<string, unknown>][] = [
        [anon, 'svc_grant_admin', { p_user: anonUserId }],
        [anonSession, 'svc_grant_admin', { p_user: anonUserId }],
        [anon, 'svc_get_profile', { p_user: anonUserId }],
        [anonSession, 'svc_get_profile', { p_user: anonUserId }],
        [anon, 'svc_upsert_rsvp', { p_activity: ids.published, p_user: null, p_subject_hash: 'a'.repeat(64), p_going: true }],
        [anonSession, 'svc_approve_group_proposal', { p_id: ids.proposal, p_admin: anonUserId, p_reason: 'x' }],
        [anon, 'svc_consume_turnstile_token', { p_hash: 'b'.repeat(64) }],
        [anon, 'svc_email_in_use', { p_email: 'x@example.org', p_exclude: anonUserId }],
      ];
      for (const [client, fn, args] of calls) {
        const r = await client.rpc(fn, args);
        expect(r.error, fn).not.toBeNull();
        expect(DENIED, fn).toContain(r.status);
      }
      const isAdmin = await svc.rpc('svc_is_admin', { p_user: anonUserId });
      expect(isAdmin.data).toBe(false);
    });
  });

  describe('whatsapp_groups', () => {
    it('anon cannot select * from the base table', async () => {
      const r = await anon.from('whatsapp_groups').select('*').eq('territory_id', hood);
      expect(r.data).toBeNull();
      expect([401, 403]).toContain(r.status);
    });

    it('anon cannot read admin columns of the base table', async () => {
      for (const col of ['created_by', 'approved_by', 'source_proposal_id', 'created_at']) {
        const r = await anon.from('whatsapp_groups').select(col).eq('territory_id', hood);
        expect(r.data, col).toBeNull();
      }
    });

    it('public view shows only active groups with the public projection', async () => {
      const r = await anon.from('whatsapp_groups_public').select('*').eq('territory_id', hood);
      expect(r.error).toBeNull();
      expect(r.data?.map((g) => g.id)).toEqual([ids.activeGroup]);
      expect(Object.keys(r.data![0]!).sort()).toEqual(['display_name', 'id', 'join_url', 'status', 'territory_id', 'updated_at']);
    });

    it('pending group is invisible to anon and anonymous sessions (view and base public columns)', async () => {
      for (const client of [anon, anonSession]) {
        const v = await client.from('whatsapp_groups_public').select('id').eq('id', ids.pendingGroup);
        expect(v.data).toEqual([]);
        const b = await client.from('whatsapp_groups').select('id,status').eq('id', ids.pendingGroup);
        expect(b.data).toEqual([]);
      }
    });

    it('anon / anonymous session cannot insert or update groups', async () => {
      const ins = await anon.from('whatsapp_groups').insert({
        territory_id: hood,
        display_name: 'Invasor',
        join_url: `https://chat.whatsapp.com/RLSinvasor${tag}`,
        status: 'active',
      });
      expect([401, 403]).toContain(ins.status);
      const upd = await anonSession.from('whatsapp_groups').update({ status: 'active' }).eq('id', ids.pendingGroup).select('id');
      expect(upd.data ?? []).toEqual([]);
      const check = await svc.from('whatsapp_groups').select('status').eq('id', ids.pendingGroup).single();
      expect(check.data?.status).toBe('pending');
    });
  });

  describe('activities', () => {
    it('anon cannot insert activities; anonymous session cannot create activities either', async () => {
      const row = {
        creator_user_id: anonUserId,
        territory_id: hood,
        title: 'Atividade invasora',
        type: 'outro',
        description: 'x'.repeat(20),
        description_sanitized: 'x'.repeat(20),
        starts_at: new Date(Date.now() + 86_400_000).toISOString(),
        public_address: 'Rua invasora 1',
        location_lon: -43.9,
        location_lat: -19.9,
        status: 'published',
      };
      const a = await anon.from('activities').insert(row);
      expect([401, 403]).toContain(a.status);
      const b = await anonSession.from('activities').insert(row);
      expect([401, 403]).toContain(b.status);
      const c = await organizer.from('activities').insert({ ...row, creator_user_id: organizerId });
      expect([401, 403]).toContain(c.status); // even verified organizers must go through the Worker
    });

    it('public view lists published/cancelled only and never exposes creator/moderation/raw fields', async () => {
      const r = await anon.from('activities_public').select('*').eq('territory_id', hood);
      expect(r.error).toBeNull();
      expect(r.data!.map((x) => x.id).sort()).toEqual([ids.published, ids.cancelled].sort());
      const keys = Object.keys(r.data![0]!);
      for (const forbidden of ['creator_user_id', 'reviewed_by', 'review_reason', 'description', 'public_contact_value', 'version']) {
        expect(keys).not.toContain(forbidden);
      }
      const creatorCol = await anon.from('activities_public').select('creator_user_id');
      expect(creatorCol.data).toBeNull();
      expect(JSON.stringify(r.data)).not.toContain(organizerId);
    });

    it('anon cannot read creator or internal columns from the base table', async () => {
      for (const col of ['*', 'creator_user_id', 'review_reason', 'description', 'public_contact_value', 'reviewed_by']) {
        const r = await anon.from('activities').select(col).eq('territory_id', hood);
        expect(r.data, col).toBeNull();
        expect([401, 403], col).toContain(r.status);
      }
    });

    it('pending activities are invisible to anon and to the anonymous session', async () => {
      for (const client of [anon, anonSession]) {
        const b = await client.from('activities').select('id').in('id', [ids.pending, ids.otherPending]);
        expect(b.data).toEqual([]);
        const v = await client.from('activities_public').select('id').in('id', [ids.pending, ids.otherPending]);
        expect(v.data).toEqual([]);
      }
    });

    it('verified organizer sees own pending row (public columns) but not someone else’s', async () => {
      const own = await organizer.from('activities').select('id,status').eq('id', ids.pending);
      expect(own.data).toEqual([{ id: ids.pending, status: 'pending_review' }]);
      const other = await organizer.from('activities').select('id').eq('id', ids.otherPending);
      expect(other.data).toEqual([]);
      const creator = await organizer.from('activities').select('creator_user_id').eq('id', ids.pending);
      expect(creator.data).toBeNull();
    });

    it('T27: switching public contact off hides it immediately in the public view', async () => {
      const before = await anon.from('activities_public').select('contact_public_value').eq('id', ids.published).single();
      expect(before.data?.contact_public_value).toBe('@contato_rls');
      await svc.from('activities').update({ public_contact_opt_in: false }).eq('id', ids.published);
      const after = await anon.from('activities_public').select('contact_public_type,contact_public_value').eq('id', ids.published).single();
      expect(after.data).toEqual({ contact_public_type: null, contact_public_value: null });
    });

    it('rsvp count is aggregate only and 0 for non-public activities', async () => {
      const r = await anon.rpc('activity_rsvp_count', { p_activity: ids.otherPending });
      expect(r.data).toBe(0);
    });
  });

  describe('transactional functions (service role)', () => {
    it('upsert_rsvp is idempotent per identity and refuses cancelled activities (T09, cancelled)', async () => {
      const subject = 'c'.repeat(64);
      const args = { p_activity: ids.published, p_user: null, p_subject_hash: subject, p_going: true };
      const one = await svc.rpc('svc_upsert_rsvp', args);
      const two = await svc.rpc('svc_upsert_rsvp', args);
      expect(one.error).toBeNull();
      expect((two.data as { rsvp_count: number }).rsvp_count).toBe(1);
      const pub = await anon.from('activities_public').select('rsvp_count').eq('id', ids.published).single();
      expect(pub.data?.rsvp_count).toBe(1);
      const other = await svc.rpc('svc_upsert_rsvp', { ...args, p_subject_hash: 'd'.repeat(64), p_going: false });
      expect(other.error?.code).toBe('PT404'); // T11: another identity cannot cancel it
      const cancelled = await svc.rpc('svc_upsert_rsvp', { ...args, p_activity: ids.cancelled });
      expect(cancelled.error?.code).toBe('PT409');
      const pending = await svc.rpc('svc_upsert_rsvp', { ...args, p_activity: ids.pending });
      expect(pending.error?.code).toBe('PT404');
    });

    it('T28: two admins approving the same proposal concurrently create exactly one group', async () => {
      const [a, b] = await Promise.all(
        admins.map((adm) => svc.rpc('svc_approve_group_proposal', { p_id: ids.proposal, p_admin: adm, p_reason: 'ok rls' })),
      );
      const results = [a!, b!];
      expect(results.filter((r) => r.error === null)).toHaveLength(1);
      expect(results.find((r) => r.error)?.error?.code).toBe('PT409');
      const groups = await svc.from('whatsapp_groups').select('id').eq('source_proposal_id', ids.proposal);
      expect(groups.data).toHaveLength(1);
    });

    it('approval by a non-admin is refused inside the function', async () => {
      const r = await svc.rpc('svc_reject_group_proposal', { p_id: ids.proposal, p_admin: anonUserId, p_reason: 'nao admin' });
      expect(r.error?.code).toBe('PT403');
    });

    it('turnstile token hash is single-use (T17)', async () => {
      const hash = (tag + 'f'.repeat(64)).slice(0, 64);
      const first = await svc.rpc('svc_consume_turnstile_token', { p_hash: hash, p_ttl_seconds: 60 });
      const second = await svc.rpc('svc_consume_turnstile_token', { p_hash: hash, p_ttl_seconds: 60 });
      expect([first.data, second.data]).toEqual([true, false]);
    });

    it('is_email_verified follows auth.users, not profile columns', async () => {
      const verified = await svc.rpc('svc_is_email_verified', { p_user: organizerId });
      const anonymous = await svc.rpc('svc_is_email_verified', { p_user: anonUserId });
      expect([verified.data, anonymous.data]).toEqual([true, false]);
    });
  });
});
